In [2]:
import pandas as pd

In [3]:
from sklearn.datasets import load_digits

In [4]:
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [11]:
lr = LogisticRegression(max_iter=5000)

In [10]:
lr = LogisticRegression(max_iter=5000)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9611111111111111

In [14]:
sv = SVC()
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

0.9888888888888889

In [15]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)


In [17]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def getscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [20]:
getscore(LogisticRegression(max_iter=5000),x_train,x_test,y_train,y_test)

0.9611111111111111

In [21]:
getscore(SVC(),x_train,x_test,y_train,y_test)

0.9888888888888889

In [22]:
getscore(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
fold = KFold(n_splits=3)

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv =fold).mean()

np.float64(0.9309961046188091)

In [26]:
cross_val_score(SVC(),digits.data,digits.target,cv = fold).mean()

np.float64(0.9677239844184752)

In [27]:
cross_val_score(LogisticRegression(max_iter=5000),digits.data,digits.target,cv = fold)

array([0.92487479, 0.94323873, 0.9148581 ])